import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'

export type Theme = 'light' | 'dark'
export type Language = 'en' | 'it' | 'es'

type Dictionary = Record<string, string>

type PreferencesValue = {
  theme: Theme
  setTheme: (theme: Theme) => void
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, vars?: Record<string, string | number>) => string
  locale: string
  countryName: (country: string | null) => string
  documentName: (documentType: string) => string
  identifierName: (identifierType: string | null) => string
}

const dictionaries: Record<Language, Dictionary> = {
  en: {
    'nav.overview': 'Overview', 'nav.accounts': 'Accounts', 'nav.memberships': 'Memberships', 'nav.travel': 'Travel', 'nav.documents': 'Documents', 'nav.notes': 'Notes', 'nav.settings': 'Settings',
    'auth.privateAccess': 'Private access', 'auth.title': 'Your personal world,\nquietly organised.', 'auth.description': 'Sign in with your authorised email using a password or a secure link.', 'auth.checkInbox': 'Check your inbox', 'auth.linkReady': 'The sign-in link is ready.', 'auth.email': 'Email address', 'auth.placeholder': 'you@example.com', 'auth.password': 'Password', 'auth.keepLoggedIn': 'Keep me logged in on this device.', 'auth.untilLogout': 'Until I log out.', 'auth.unableSend': 'Unable to send the sign-in link. Try again.', 'auth.rateLimited': 'Too many email requests. Wait an hour or sign in with your password.', 'auth.invalidCredentials': 'Incorrect email or password.', 'auth.sending': 'Sending…', 'auth.signingIn': 'Signing in…', 'auth.sendLink': 'Send secure link', 'auth.signIn': 'Sign in', 'auth.usePassword': 'Sign in with password instead', 'auth.useLink': 'Send me a secure link instead', 'auth.protected': 'Protected by authentication and row-level security',
    'status.active': 'Active', 'status.pending': 'Pending', 'status.uploaded': 'Uploaded', 'status.not_uploaded': 'Not uploaded', 'status.connected': 'Connected', 'status.not_connected': 'Not connected', 'status.connecting': 'Connecting', 'status.selection_required': 'Action required', 'status.action_required': 'Action required', 'status.reconnect_required': 'Reconnect required', 'status.temporarily_unavailable': 'Temporarily unavailable', 'status.disconnected': 'Disconnected',
    'bank.overview': 'Overview', 'bank.transactions': 'Transactions', 'bank.currentBalance': 'Current balance', 'bank.currentAccount': 'Current account', 'bank.openBankingReadOnly': 'Live from Open Banking · read only', 'bank.savingsBalance': 'Salvadanaio savings', 'bank.available': 'Available', 'bank.connect': 'Connect bank', 'bank.reconnect': 'Reconnect bank', 'bank.refresh': 'Refresh', 'bank.refreshing': 'Refreshing…', 'bank.refreshed': 'Account updated', 'bank.cooldown': 'Please wait before refreshing again', 'bank.refreshFailed': 'Unable to refresh', 'bank.unableRefresh': 'Unable to refresh. Your last successful data is still available.', 'bank.lastSynced': 'Last synced', 'bank.connectDescription': 'Connect securely through Enable Banking to view balances and transactions. Private Hub never asks for your banking password.', 'bank.notAvailable': 'Open Banking is not available for this account.', 'bank.notConfigured': 'Enable Banking needs to be activated first', 'bank.connectFailed': 'Unable to start the bank connection', 'bank.chooseAccount': 'Choose the correct account', 'bank.chooseAccountText': 'More than one account was returned. Select the matching account once.', 'bank.accountSelected': 'Bank account connected', 'bank.selectionFailed': 'Unable to select this account', 'bank.noTransactions': 'No transactions have been synchronised yet.', 'bank.connectForTransactions': 'Connect the bank to view transactions.', 'bank.transaction': 'Transaction', 'bank.pending': 'Pending', 'bank.manualBalance': 'Manual balance', 'bank.manualHint': 'Updated by you and not synchronised with the bank.', 'bank.manualAmount': 'Balance', 'bank.manualSave': 'Save balance', 'bank.manualSaved': 'Manual balance saved', 'bank.manualInvalid': 'Enter a valid balance',
    'account.applicationPending': 'Application pending', 'account.identifierSecured': '{{type}} secured', 'account.noIdentifier': 'No identifier added', 'account.account': 'Account', 'account.details': 'Account details', 'account.country': 'Country', 'account.notAdded': 'Not added', 'account.notes': 'Notes', 'account.pendingText': 'Details can be added once the account is active.', 'account.copyIdentifier': 'Copy {{type}}',
    'membership.membership': 'Membership', 'membership.numberState': 'Membership number {{state}}', 'membership.secured': 'secured', 'membership.notAddedLower': 'not added', 'membership.details': 'Membership details', 'membership.number': 'Membership number', 'membership.copyNumber': 'Copy number', 'membership.tier': 'Tier', 'membership.points': 'Points / miles', 'membership.notConnected': 'Not connected', 'membership.memberSince': 'Member since',
    'common.copied': 'Copied', 'common.close': 'Close', 'common.open': 'Open', 'common.viewAll': 'View all', 'common.save': 'Save', 'common.saving': 'Saving…', 'common.delete': 'Delete', 'common.download': 'Download', 'common.replace': 'Replace', 'common.view': 'View',
    'documents.uploaded': 'Files uploaded securely', 'documents.uploadFailed': 'Upload failed', 'documents.deleteConfirm': 'Delete {{name}}? This cannot be undone.', 'documents.deleted': 'File deleted', 'documents.deleteFailed': 'Unable to delete file', 'documents.readyUpload': 'Ready for a secure upload', 'documents.licencePending': 'Driving licence conversion pending', 'documents.uploading': 'Uploading…', 'documents.upload': 'Upload files', 'documents.addFiles': 'Add files', 'documents.fileCount': 'Files stored: {{count}}', 'documents.files': 'Document files', 'documents.previewTitle': 'Secure preview', 'documents.filePosition': 'File {{current}} of {{total}}', 'documents.loadingPreview': 'Loading secure preview…', 'documents.previewUnavailable': 'A visual preview is not available for this file type.', 'documents.previewFailed': 'Unable to open the preview', 'documents.previousFile': 'Previous file', 'documents.nextFile': 'Next file', 'documents.downloadFile': 'Download {{name}}', 'documents.deleteFile': 'Delete {{name}}', 'documents.privateStorage': 'Private storage', 'documents.identityHealth': 'Identity and health documents', 'documents.personalRecords': 'Personal records', 'documents.payslipsSection': 'Payslips', 'documents.payslipsText': 'Keep every payslip together and add more whenever you need.', 'documents.miscellaneousSection': 'Miscellaneous', 'documents.miscellaneousText': 'Secure storage for documents that do not fit another section.',
    'notes.connect': 'Connect Supabase to save notes', 'notes.saved': 'Note saved', 'notes.saveFailed': 'Unable to save note', 'notes.privateWriting': 'Private writing', 'notes.new': 'New note', 'notes.deleteLabel': 'Delete {{title}}', 'notes.deleteConfirm': 'Delete “{{title}}”?', 'notes.deleted': 'Note deleted', 'notes.emptyTitle': 'No notes yet', 'notes.emptyText': 'Create a private note when you have something worth keeping.', 'notes.privateNote': 'Private note', 'notes.title': 'Note title', 'notes.startWriting': 'Start writing…', 'notes.save': 'Save note',
    'records.connect': 'Connect Supabase to add private records', 'records.accountAdded': 'Account added', 'records.membershipAdded': 'Membership added', 'records.saveFailed': 'Unable to save this record', 'records.privateRecord': 'Private record', 'records.addAccount': 'Add account', 'records.addMembership': 'Add membership', 'records.institution': 'Institution', 'records.product': 'Product', 'records.country': 'Country', 'records.identifierType': 'Identifier type', 'records.identifierHint': 'IBAN, email, customer ID…', 'records.identifierValue': 'Identifier value', 'records.provider': 'Provider', 'records.programme': 'Programme', 'records.membershipNumber': 'Membership number', 'records.storageHint': 'This record is stored in the private database and scoped to your account.',
    'app.connectFailed': 'Unable to connect', 'app.primaryNavigation': 'Primary navigation', 'app.privateSpace': 'Your private space', 'app.securePreview': 'Secure preview', 'app.encryptedAccess': 'Encrypted access', 'app.closeNavigation': 'Close navigation', 'app.openNavigation': 'Open navigation', 'app.search': 'Search your hub…', 'app.previewMode': 'Secure preview mode', 'app.preview': 'Preview', 'app.personal': 'Personal', 'app.offline': 'You’re offline. Private data is not cached.',
    'overview.eyebrow': 'Personal overview', 'overview.welcome': 'Welcome back, Gianluca.', 'overview.subtitle': 'Everything important, calmly in reach.', 'overview.accounts': 'Accounts', 'overview.quickAccess': 'Quick access', 'overview.uploadDocument': 'Upload document', 'overview.openNotes': 'Open notes', 'overview.memberships': 'Memberships', 'overview.documents': 'Documents', 'overview.italianAwaiting': 'Italian documents awaiting upload', 'overview.brazilianAwaiting': 'Brazilian documents awaiting upload', 'overview.licenceConversion': 'Driving licence conversion',
    'savings.eyebrow': 'W212 savings plan', 'savings.title': 'Salvadanaio, week by week', 'savings.goal': '€8K–€12K goal', 'savings.current': 'Current savings', 'savings.weeklyChange': 'Weekly change', 'savings.chartLabel': 'Weekly Salvadanaio balance history', 'savings.emptyTitle': 'Your first update starts the chart', 'savings.emptyText': 'No earlier values are invented. Save the Salvadanaio balance to begin a real weekly history.', 'savings.toMinimum': 'Progress to €8K', 'savings.reviewEyebrow': 'Data-driven review', 'savings.reviewTitle': 'A calm look at your money', 'savings.reviewMovements': 'Across the latest 30 days of recorded Movimenti, {{count}} day-to-day entries show {{spent}} going out and {{received}} coming in.', 'savings.reviewTransfers': '{{count}} transfer(s) totalling {{amount}} into Salvadanaio are treated as savings, not spending.', 'savings.reviewLargest': 'The largest outgoing was {{amount}} at {{name}}.', 'savings.reviewRecurring': '{{name}} appears {{count}} times, so it is worth checking whether it is expected or can be trimmed.', 'savings.reviewNoRecurring': 'No repeated outgoing description stands out in this period.', 'savings.reviewEmpty': 'There are not enough synced Intesa Movimenti yet for an honest spending review. Refresh the connected account and this review will use the real entries.', 'savings.momentumStart': 'Add your Salvadanaio amount to establish the first honest checkpoint for the W212 goal.', 'savings.momentumFirst': 'You have {{amount}} set aside. Keep the purchase target separate from insurance, maintenance and registration costs.', 'savings.momentumUp': 'Savings are up {{amount}} from the previous recorded week. That is useful momentum—keep it sustainable.', 'savings.momentumDown': 'Savings are down {{amount}} from the previous recorded week. No judgement: check Movimenti, identify what changed, and reset the next realistic step.', 'savings.reviewNote': 'Generated locally from your real Movimenti and Salvadanaio history; no transaction details are sent to an AI service. Budgeting guidance, not financial advice.',
    'pages.financialServices': 'Financial services', 'pages.loyalty': 'Loyalty programmes', 'pages.journeys': 'Journeys', 'pages.travelEmptyTitle': 'No trips added yet', 'pages.travelEmptyText': 'Travel plans will appear here when you’re ready to add them.',
    'settings.integrations': 'Integrations', 'settings.gmailText': 'Connector status only. Inbox access is disabled.', 'settings.supabaseText': 'Authentication, private data and document storage.', 'settings.bankingText': 'Read-only balances and transactions. Payments are disabled.', 'settings.privacy': 'Privacy', 'settings.privateByDesign': 'Private by design', 'settings.privacyText': 'Identifiers appear only after authentication. Sensitive API responses are never cached by the service worker.',
    'settings.personalisation': 'Personalisation', 'settings.appearance': 'Appearance', 'settings.appearanceText': 'Choose the visual style that feels most comfortable.', 'settings.light': 'Light', 'settings.dark': 'Dark', 'settings.language': 'Language', 'settings.languageText': 'Choose the language used throughout Private Hub.', 'settings.english': 'English', 'settings.italian': 'Italiano', 'settings.spanish': 'Español', 'settings.security': 'Security', 'settings.password': 'Password', 'settings.passwordText': 'Set or change the password used to sign in.', 'settings.newPassword': 'New password', 'settings.confirmPassword': 'Confirm password', 'settings.setPassword': 'Set password', 'settings.passwordMismatch': 'The passwords do not match.', 'settings.passwordFailed': 'The password could not be saved.', 'settings.passwordSaved': 'Password saved.',
    'country.Italy': 'Italy', 'country.Brazil': 'Brazil',
    'identifier.Email': 'Email', 'identifier.IBAN': 'IBAN', 'identifier.Chave PIX': 'Chave PIX',
    'document.Passport': 'Passport', 'document.Carta d’identità': 'Carta d’identità', 'document.Carta d\'identità': 'Carta d’identità', 'document.Tessera Sanitaria': 'Tessera Sanitaria', 'document.Patente italiana': 'Patente italiana', 'document.RG': 'RG', 'document.CPF': 'CPF', 'document.CNH': 'CNH', 'document.Payslips': 'Payslips', 'document.Miscellaneous': 'Miscellaneous',
  },
  it: {
    'nav.overview': 'Panoramica', 'nav.accounts': 'Conti', 'nav.memberships': 'Programmi fedeltà', 'nav.travel': 'Viaggi', 'nav.documents': 'Documenti', 'nav.notes': 'Note', 'nav.settings': 'Impostazioni',
    'auth.privateAccess': 'Accesso privato', 'auth.title': 'Il tuo mondo personale,\norganizzato con discrezione.', 'auth.description': 'Accedi con la tua email autorizzata usando la password o un link sicuro.', 'auth.checkInbox': 'Controlla la posta', 'auth.linkReady': 'Il link di accesso è pronto.', 'auth.email': 'Indirizzo email', 'auth.placeholder': 'tu@esempio.com', 'auth.password': 'Password', 'auth.keepLoggedIn': 'Mantieni l’accesso su questo dispositivo.', 'auth.untilLogout': 'Finché non esco.', 'auth.unableSend': 'Impossibile inviare il link di accesso. Riprova.', 'auth.rateLimited': 'Troppe richieste email. Attendi un’ora o accedi con la password.', 'auth.invalidCredentials': 'Email o password non corretti.', 'auth.sending': 'Invio…', 'auth.signingIn': 'Accesso…', 'auth.sendLink': 'Invia link sicuro', 'auth.signIn': 'Accedi', 'auth.usePassword': 'Accedi con la password', 'auth.useLink': 'Inviami un link sicuro', 'auth.protected': 'Protetto da autenticazione e sicurezza a livello di riga',
    'status.active': 'Attivo', 'status.pending': 'In attesa', 'status.uploaded': 'Caricato', 'status.not_uploaded': 'Non caricato', 'status.connected': 'Connesso', 'status.not_connected': 'Non connesso', 'status.connecting': 'Connessione in corso', 'status.selection_required': 'Azione richiesta', 'status.action_required': 'Azione richiesta', 'status.reconnect_required': 'Riconnessione richiesta', 'status.temporarily_unavailable': 'Temporaneamente non disponibile', 'status.disconnected': 'Disconnesso',
    'bank.overview': 'Panoramica', 'bank.transactions': 'Movimenti', 'bank.currentBalance': 'Saldo attuale', 'bank.currentAccount': 'Conto corrente', 'bank.openBankingReadOnly': 'Dati Open Banking · sola lettura', 'bank.savingsBalance': 'Risparmi nel Salvadanaio', 'bank.available': 'Disponibile', 'bank.connect': 'Collega banca', 'bank.reconnect': 'Ricollega banca', 'bank.refresh': 'Aggiorna', 'bank.refreshing': 'Aggiornamento…', 'bank.refreshed': 'Conto aggiornato', 'bank.cooldown': 'Attendi prima di aggiornare di nuovo', 'bank.refreshFailed': 'Impossibile aggiornare', 'bank.unableRefresh': 'Impossibile aggiornare. Gli ultimi dati riusciti restano disponibili.', 'bank.lastSynced': 'Ultimo aggiornamento', 'bank.connectDescription': 'Collegati in modo sicuro tramite Enable Banking per vedere saldi e movimenti. Private Hub non chiede mai la password bancaria.', 'bank.notAvailable': 'Open Banking non è disponibile per questo conto.', 'bank.notConfigured': 'Enable Banking deve prima essere attivato', 'bank.connectFailed': 'Impossibile avviare il collegamento bancario', 'bank.chooseAccount': 'Scegli il conto corretto', 'bank.chooseAccountText': 'Sono stati restituiti più conti. Seleziona una volta quello corrispondente.', 'bank.accountSelected': 'Conto bancario collegato', 'bank.selectionFailed': 'Impossibile selezionare questo conto', 'bank.noTransactions': 'Nessun movimento sincronizzato.', 'bank.connectForTransactions': 'Collega la banca per vedere i movimenti.', 'bank.transaction': 'Movimento', 'bank.pending': 'In attesa', 'bank.manualBalance': 'Saldo manuale', 'bank.manualHint': 'Aggiornato da te e non sincronizzato con la banca.', 'bank.manualAmount': 'Saldo', 'bank.manualSave': 'Salva saldo', 'bank.manualSaved': 'Saldo manuale salvato', 'bank.manualInvalid': 'Inserisci un saldo valido',
    'account.applicationPending': 'Richiesta in attesa', 'account.identifierSecured': '{{type}} protetto', 'account.noIdentifier': 'Nessun identificativo aggiunto', 'account.account': 'Conto', 'account.details': 'Dettagli del conto', 'account.country': 'Paese', 'account.notAdded': 'Non aggiunto', 'account.notes': 'Note', 'account.pendingText': 'I dettagli potranno essere aggiunti quando il conto sarà attivo.', 'account.copyIdentifier': 'Copia {{type}}',
    'membership.membership': 'Programma', 'membership.numberState': 'Numero iscrizione {{state}}', 'membership.secured': 'protetto', 'membership.notAddedLower': 'non aggiunto', 'membership.details': 'Dettagli del programma', 'membership.number': 'Numero iscrizione', 'membership.copyNumber': 'Copia numero', 'membership.tier': 'Livello', 'membership.points': 'Punti / miglia', 'membership.notConnected': 'Non connesso', 'membership.memberSince': 'Iscritto dal',
    'common.copied': 'Copiato', 'common.close': 'Chiudi', 'common.open': 'Apri', 'common.viewAll': 'Vedi tutti', 'common.save': 'Salva', 'common.saving': 'Salvataggio…', 'common.delete': 'Elimina', 'common.download': 'Scarica', 'common.replace': 'Sostituisci', 'common.view': 'Visualizza',
    'documents.uploaded': 'File caricati in modo sicuro', 'documents.uploadFailed': 'Caricamento non riuscito', 'documents.deleteConfirm': 'Eliminare {{name}}? L’operazione non può essere annullata.', 'documents.deleted': 'File eliminato', 'documents.deleteFailed': 'Impossibile eliminare il file', 'documents.readyUpload': 'Pronto per un caricamento sicuro', 'documents.licencePending': 'Conversione della patente in attesa', 'documents.uploading': 'Caricamento…', 'documents.upload': 'Carica file', 'documents.addFiles': 'Aggiungi file', 'documents.fileCount': 'File archiviati: {{count}}', 'documents.files': 'File del documento', 'documents.previewTitle': 'Anteprima sicura', 'documents.filePosition': 'File {{current}} di {{total}}', 'documents.loadingPreview': 'Caricamento anteprima sicura…', 'documents.previewUnavailable': 'L’anteprima visiva non è disponibile per questo tipo di file.', 'documents.previewFailed': 'Impossibile aprire l’anteprima', 'documents.previousFile': 'File precedente', 'documents.nextFile': 'File successivo', 'documents.downloadFile': 'Scarica {{name}}', 'documents.deleteFile': 'Elimina {{name}}', 'documents.privateStorage': 'Archivio privato', 'documents.identityHealth': 'Documenti di identità e sanitari', 'documents.personalRecords': 'Documenti personali', 'documents.payslipsSection': 'Buste paga', 'documents.payslipsText': 'Conserva qui tutte le buste paga e aggiungine altre quando vuoi.', 'documents.miscellaneousSection': 'Varie', 'documents.miscellaneousText': 'Archivio sicuro per i documenti che non rientrano nelle altre sezioni.',
    'notes.connect': 'Collega Supabase per salvare le note', 'notes.saved': 'Nota salvata', 'notes.saveFailed': 'Impossibile salvare la nota', 'notes.privateWriting': 'Scrittura privata', 'notes.new': 'Nuova nota', 'notes.deleteLabel': 'Elimina {{title}}', 'notes.deleteConfirm': 'Eliminare “{{title}}”?', 'notes.deleted': 'Nota eliminata', 'notes.emptyTitle': 'Nessuna nota', 'notes.emptyText': 'Crea una nota privata quando hai qualcosa che desideri conservare.', 'notes.privateNote': 'Nota privata', 'notes.title': 'Titolo della nota', 'notes.startWriting': 'Inizia a scrivere…', 'notes.save': 'Salva nota',
    'records.connect': 'Collega Supabase per aggiungere dati privati', 'records.accountAdded': 'Conto aggiunto', 'records.membershipAdded': 'Programma aggiunto', 'records.saveFailed': 'Impossibile salvare questo elemento', 'records.privateRecord': 'Dato privato', 'records.addAccount': 'Aggiungi conto', 'records.addMembership': 'Aggiungi programma', 'records.institution': 'Istituto', 'records.product': 'Prodotto', 'records.country': 'Paese', 'records.identifierType': 'Tipo di identificativo', 'records.identifierHint': 'IBAN, email, ID cliente…', 'records.identifierValue': 'Valore identificativo', 'records.provider': 'Fornitore', 'records.programme': 'Programma', 'records.membershipNumber': 'Numero iscrizione', 'records.storageHint': 'Questo dato viene salvato nel database privato ed è accessibile esclusivamente dal tuo account.',
    'app.connectFailed': 'Impossibile connettersi', 'app.primaryNavigation': 'Navigazione principale', 'app.privateSpace': 'Il tuo spazio privato', 'app.securePreview': 'Anteprima sicura', 'app.encryptedAccess': 'Accesso protetto', 'app.closeNavigation': 'Chiudi navigazione', 'app.openNavigation': 'Apri navigazione', 'app.search': 'Cerca nel tuo hub…', 'app.previewMode': 'Modalità anteprima sicura', 'app.preview': 'Anteprima', 'app.personal': 'Personale', 'app.offline': 'Sei offline. I dati privati non vengono memorizzati nella cache.',
    'overview.eyebrow': 'Panoramica personale', 'overview.welcome': 'Bentornato, Gianluca.', 'overview.subtitle': 'Tutto ciò che conta, sempre a portata di mano.', 'overview.accounts': 'Conti', 'overview.quickAccess': 'Accesso rapido', 'overview.uploadDocument': 'Carica documento', 'overview.openNotes': 'Apri note', 'overview.memberships': 'Programmi fedeltà', 'overview.documents': 'Documenti', 'overview.italianAwaiting': 'Documenti italiani da caricare', 'overview.brazilianAwaiting': 'Documenti brasiliani da caricare', 'overview.licenceConversion': 'Conversione patente',
    'savings.eyebrow': 'Piano risparmio W212', 'savings.title': 'Salvadanaio, settimana dopo settimana', 'savings.goal': 'Obiettivo €8K–€12K', 'savings.current': 'Risparmi attuali', 'savings.weeklyChange': 'Variazione settimanale', 'savings.chartLabel': 'Storico settimanale del saldo Salvadanaio', 'savings.emptyTitle': 'Il primo aggiornamento avvia il grafico', 'savings.emptyText': 'Nessun valore precedente viene inventato. Salva il saldo del Salvadanaio per iniziare uno storico reale.', 'savings.toMinimum': 'Progresso verso €8K', 'savings.reviewEyebrow': 'Analisi basata sui dati', 'savings.reviewTitle': 'Uno sguardo sereno alle tue finanze', 'savings.reviewMovements': 'Negli ultimi 30 giorni registrati, {{count}} Movimenti quotidiani mostrano {{spent}} in uscita e {{received}} in entrata.', 'savings.reviewTransfers': '{{count}} trasferimenti per {{amount}} verso il Salvadanaio sono conteggiati come risparmio, non come spesa.', 'savings.reviewLargest': 'L’uscita più alta è stata di {{amount}} presso {{name}}.', 'savings.reviewRecurring': '{{name}} compare {{count}} volte: vale la pena verificare se è una spesa prevista o riducibile.', 'savings.reviewNoRecurring': 'In questo periodo non emerge una descrizione di spesa ripetuta.', 'savings.reviewEmpty': 'Non ci sono ancora abbastanza Movimenti Intesa sincronizzati per un’analisi onesta. Aggiorna il conto collegato e questa sezione userà le voci reali.', 'savings.momentumStart': 'Aggiungi il saldo del Salvadanaio per creare il primo punto reale verso l’obiettivo W212.', 'savings.momentumFirst': 'Hai messo da parte {{amount}}. Mantieni il prezzo d’acquisto separato dai costi di assicurazione, manutenzione e immatricolazione.', 'savings.momentumUp': 'I risparmi sono saliti di {{amount}} rispetto alla settimana precedente registrata. È un buon ritmo: rendilo sostenibile.', 'savings.momentumDown': 'I risparmi sono scesi di {{amount}} rispetto alla settimana precedente registrata. Nessun giudizio: controlla i Movimenti, individua cosa è cambiato e fissa il prossimo passo realistico.', 'savings.reviewNote': 'Generata localmente dai tuoi Movimenti reali e dallo storico Salvadanaio; nessun dettaglio viene inviato a un servizio AI. Indicazioni di budgeting, non consulenza finanziaria.',
    'pages.financialServices': 'Servizi finanziari', 'pages.loyalty': 'Programmi fedeltà', 'pages.journeys': 'Viaggi', 'pages.travelEmptyTitle': 'Nessun viaggio aggiunto', 'pages.travelEmptyText': 'I tuoi programmi di viaggio appariranno qui quando vorrai aggiungerli.',
    'settings.integrations': 'Integrazioni', 'settings.gmailText': 'Solo stato della connessione. L’accesso alla posta è disattivato.', 'settings.supabaseText': 'Autenticazione, dati privati e archivio documenti.', 'settings.bankingText': 'Saldi e movimenti in sola lettura. I pagamenti sono disattivati.', 'settings.privacy': 'Privacy', 'settings.privateByDesign': 'Privato per impostazione', 'settings.privacyText': 'Gli identificativi sono visibili solo dopo l’autenticazione. Le risposte sensibili delle API non vengono mai memorizzate nella cache dal service worker.',
    'settings.personalisation': 'Personalizzazione', 'settings.appearance': 'Aspetto', 'settings.appearanceText': 'Scegli lo stile visivo che preferisci.', 'settings.light': 'Chiaro', 'settings.dark': 'Scuro', 'settings.language': 'Lingua', 'settings.languageText': 'Scegli la lingua utilizzata in tutto Private Hub.', 'settings.english': 'English', 'settings.italian': 'Italiano', 'settings.spanish': 'Español', 'settings.security': 'Sicurezza', 'settings.password': 'Password', 'settings.passwordText': 'Imposta o modifica la password usata per accedere.', 'settings.newPassword': 'Nuova password', 'settings.confirmPassword': 'Conferma password', 'settings.setPassword': 'Imposta password', 'settings.passwordMismatch': 'Le password non coincidono.', 'settings.passwordFailed': 'Impossibile salvare la password.', 'settings.passwordSaved': 'Password salvata.',
    'country.Italy': 'Italia', 'country.Brazil': 'Brasile',
    'identifier.Email': 'Email', 'identifier.IBAN': 'IBAN', 'identifier.Chave PIX': 'Chave PIX',
    'document.Passport': 'Passaporto', 'document.Carta d’identità': 'Carta d’identità', 'document.Carta d\'identità': 'Carta d’identità', 'document.Tessera Sanitaria': 'Tessera Sanitaria', 'document.Patente italiana': 'Patente italiana', 'document.RG': 'RG', 'document.CPF': 'CPF', 'document.CNH': 'CNH', 'document.Payslips': 'Buste paga', 'document.Miscellaneous': 'Varie',
  },
  es: {
    'nav.overview': 'Resumen', 'nav.accounts': 'Cuentas', 'nav.memberships': 'Membresías', 'nav.travel': 'Viajes', 'nav.documents': 'Documentos', 'nav.notes': 'Notas', 'nav.settings': 'Ajustes',
    'auth.privateAccess': 'Acceso privado', 'auth.title': 'Tu mundo personal,\norganizado con discreción.', 'auth.description': 'Inicia sesión con tu correo autorizado usando contraseña o un enlace seguro.', 'auth.checkInbox': 'Revisa tu correo', 'auth.linkReady': 'El enlace de acceso está listo.', 'auth.email': 'Correo electrónico', 'auth.placeholder': 'tu@ejemplo.com', 'auth.password': 'Contraseña', 'auth.keepLoggedIn': 'Mantener mi sesión en este dispositivo.', 'auth.untilLogout': 'Hasta que cierre sesión.', 'auth.unableSend': 'No se pudo enviar el enlace de acceso. Inténtalo de nuevo.', 'auth.rateLimited': 'Demasiadas solicitudes de correo. Espera una hora o inicia sesión con tu contraseña.', 'auth.invalidCredentials': 'Correo o contraseña incorrectos.', 'auth.sending': 'Enviando…', 'auth.signingIn': 'Iniciando sesión…', 'auth.sendLink': 'Enviar enlace seguro', 'auth.signIn': 'Iniciar sesión', 'auth.usePassword': 'Iniciar sesión con contraseña', 'auth.useLink': 'Enviarme un enlace seguro', 'auth.protected': 'Protegido mediante autenticación y seguridad a nivel de fila',
    'status.active': 'Activo', 'status.pending': 'Pendiente', 'status.uploaded': 'Subido', 'status.not_uploaded': 'Sin subir', 'status.connected': 'Conectado', 'status.not_connected': 'No conectado', 'status.connecting': 'Conectando', 'status.selection_required': 'Acción necesaria', 'status.action_required': 'Acción necesaria', 'status.reconnect_required': 'Reconexión necesaria', 'status.temporarily_unavailable': 'Temporalmente no disponible', 'status.disconnected': 'Desconectado',
    'bank.overview': 'Resumen', 'bank.transactions': 'Movimientos', 'bank.currentBalance': 'Saldo actual', 'bank.currentAccount': 'Cuenta corriente', 'bank.openBankingReadOnly': 'Datos Open Banking · solo lectura', 'bank.savingsBalance': 'Ahorros en Salvadanaio', 'bank.available': 'Disponible', 'bank.connect': 'Conectar banco', 'bank.reconnect': 'Reconectar banco', 'bank.refresh': 'Actualizar', 'bank.refreshing': 'Actualizando…', 'bank.refreshed': 'Cuenta actualizada', 'bank.cooldown': 'Espera antes de actualizar de nuevo', 'bank.refreshFailed': 'No se pudo actualizar', 'bank.unableRefresh': 'No se pudo actualizar. Los últimos datos correctos siguen disponibles.', 'bank.lastSynced': 'Última sincronización', 'bank.connectDescription': 'Conecta de forma segura mediante Enable Banking para ver saldos y movimientos. Private Hub nunca solicita tu contraseña bancaria.', 'bank.notAvailable': 'Open Banking no está disponible para esta cuenta.', 'bank.notConfigured': 'Primero hay que activar Enable Banking', 'bank.connectFailed': 'No se pudo iniciar la conexión bancaria', 'bank.chooseAccount': 'Elige la cuenta correcta', 'bank.chooseAccountText': 'Se devolvió más de una cuenta. Selecciona una vez la cuenta correspondiente.', 'bank.accountSelected': 'Cuenta bancaria conectada', 'bank.selectionFailed': 'No se pudo seleccionar esta cuenta', 'bank.noTransactions': 'Aún no se han sincronizado movimientos.', 'bank.connectForTransactions': 'Conecta el banco para ver los movimientos.', 'bank.transaction': 'Movimiento', 'bank.pending': 'Pendiente', 'bank.manualBalance': 'Saldo manual', 'bank.manualHint': 'Actualizado por ti y no sincronizado con el banco.', 'bank.manualAmount': 'Saldo', 'bank.manualSave': 'Guardar saldo', 'bank.manualSaved': 'Saldo manual guardado', 'bank.manualInvalid': 'Introduce un saldo válido',
    'account.applicationPending': 'Solicitud pendiente', 'account.identifierSecured': '{{type}} protegido', 'account.noIdentifier': 'Sin identificador añadido', 'account.account': 'Cuenta', 'account.details': 'Detalles de la cuenta', 'account.country': 'País', 'account.notAdded': 'Sin añadir', 'account.notes': 'Notas', 'account.pendingText': 'Los detalles podrán añadirse cuando la cuenta esté activa.', 'account.copyIdentifier': 'Copiar {{type}}',
    'membership.membership': 'Membresía', 'membership.numberState': 'Número de membresía {{state}}', 'membership.secured': 'protegido', 'membership.notAddedLower': 'sin añadir', 'membership.details': 'Detalles de la membresía', 'membership.number': 'Número de membresía', 'membership.copyNumber': 'Copiar número', 'membership.tier': 'Nivel', 'membership.points': 'Puntos / millas', 'membership.notConnected': 'No conectado', 'membership.memberSince': 'Miembro desde',
    'common.copied': 'Copiado', 'common.close': 'Cerrar', 'common.open': 'Abrir', 'common.viewAll': 'Ver todo', 'common.save': 'Guardar', 'common.saving': 'Guardando…', 'common.delete': 'Eliminar', 'common.download': 'Descargar', 'common.replace': 'Sustituir', 'common.view': 'Ver',
    'documents.uploaded': 'Archivos subidos de forma segura', 'documents.uploadFailed': 'Error al subir los archivos', 'documents.deleteConfirm': '¿Eliminar {{name}}? Esta acción no se puede deshacer.', 'documents.deleted': 'Archivo eliminado', 'documents.deleteFailed': 'No se pudo eliminar el archivo', 'documents.readyUpload': 'Listo para una carga segura', 'documents.licencePending': 'Conversión del permiso de conducir pendiente', 'documents.uploading': 'Subiendo…', 'documents.upload': 'Subir archivos', 'documents.addFiles': 'Añadir archivos', 'documents.fileCount': 'Archivos guardados: {{count}}', 'documents.files': 'Archivos del documento', 'documents.previewTitle': 'Vista previa segura', 'documents.filePosition': 'Archivo {{current}} de {{total}}', 'documents.loadingPreview': 'Cargando vista previa segura…', 'documents.previewUnavailable': 'No hay vista previa visual para este tipo de archivo.', 'documents.previewFailed': 'No se pudo abrir la vista previa', 'documents.previousFile': 'Archivo anterior', 'documents.nextFile': 'Archivo siguiente', 'documents.downloadFile': 'Descargar {{name}}', 'documents.deleteFile': 'Eliminar {{name}}', 'documents.privateStorage': 'Archivo privado', 'documents.identityHealth': 'Documentos de identidad y sanitarios', 'documents.personalRecords': 'Documentos personales', 'documents.payslipsSection': 'Nóminas', 'documents.payslipsText': 'Guarda aquí todas tus nóminas y añade más cuando lo necesites.', 'documents.miscellaneousSection': 'Varios', 'documents.miscellaneousText': 'Almacenamiento seguro para documentos que no encajan en otra sección.',
    'notes.connect': 'Conecta Supabase para guardar notas', 'notes.saved': 'Nota guardada', 'notes.saveFailed': 'No se pudo guardar la nota', 'notes.privateWriting': 'Escritura privada', 'notes.new': 'Nueva nota', 'notes.deleteLabel': 'Eliminar {{title}}', 'notes.deleteConfirm': '¿Eliminar “{{title}}”?', 'notes.deleted': 'Nota eliminada', 'notes.emptyTitle': 'Aún no hay notas', 'notes.emptyText': 'Crea una nota privada cuando tengas algo que quieras conservar.', 'notes.privateNote': 'Nota privada', 'notes.title': 'Título de la nota', 'notes.startWriting': 'Empieza a escribir…', 'notes.save': 'Guardar nota',
    'records.connect': 'Conecta Supabase para añadir datos privados', 'records.accountAdded': 'Cuenta añadida', 'records.membershipAdded': 'Membresía añadida', 'records.saveFailed': 'No se pudo guardar este registro', 'records.privateRecord': 'Registro privado', 'records.addAccount': 'Añadir cuenta', 'records.addMembership': 'Añadir membresía', 'records.institution': 'Entidad', 'records.product': 'Producto', 'records.country': 'País', 'records.identifierType': 'Tipo de identificador', 'records.identifierHint': 'IBAN, correo, ID de cliente…', 'records.identifierValue': 'Valor del identificador', 'records.provider': 'Proveedor', 'records.programme': 'Programa', 'records.membershipNumber': 'Número de membresía', 'records.storageHint': 'Este registro se guarda en la base de datos privada y queda limitado a tu cuenta.',
    'app.connectFailed': 'No se pudo conectar', 'app.primaryNavigation': 'Navegación principal', 'app.privateSpace': 'Tu espacio privado', 'app.securePreview': 'Vista previa segura', 'app.encryptedAccess': 'Acceso protegido', 'app.closeNavigation': 'Cerrar navegación', 'app.openNavigation': 'Abrir navegación', 'app.search': 'Buscar en tu hub…', 'app.previewMode': 'Modo de vista previa segura', 'app.preview': 'Vista previa', 'app.personal': 'Personal', 'app.offline': 'Estás sin conexión. Los datos privados no se guardan en caché.',
    'overview.eyebrow': 'Resumen personal', 'overview.welcome': 'Bienvenido de nuevo, Gianluca.', 'overview.subtitle': 'Todo lo importante, siempre a tu alcance.', 'overview.accounts': 'Cuentas', 'overview.quickAccess': 'Acceso rápido', 'overview.uploadDocument': 'Subir documento', 'overview.openNotes': 'Abrir notas', 'overview.memberships': 'Membresías', 'overview.documents': 'Documentos', 'overview.italianAwaiting': 'Documentos italianos pendientes de subir', 'overview.brazilianAwaiting': 'Documentos brasileños pendientes de subir', 'overview.licenceConversion': 'Conversión del permiso',
    'savings.eyebrow': 'Plan de ahorro W212', 'savings.title': 'Salvadanaio, semana a semana', 'savings.goal': 'Objetivo €8K–€12K', 'savings.current': 'Ahorro actual', 'savings.weeklyChange': 'Cambio semanal', 'savings.chartLabel': 'Historial semanal del saldo Salvadanaio', 'savings.emptyTitle': 'Tu primera actualización inicia el gráfico', 'savings.emptyText': 'No se inventan valores anteriores. Guarda el saldo de Salvadanaio para iniciar un historial real.', 'savings.toMinimum': 'Progreso hacia €8K', 'savings.reviewEyebrow': 'Análisis basado en datos', 'savings.reviewTitle': 'Una mirada tranquila a tus finanzas', 'savings.reviewMovements': 'En los últimos 30 días registrados, {{count}} Movimientos cotidianos muestran {{spent}} de salidas y {{received}} de entradas.', 'savings.reviewTransfers': '{{count}} transferencias por {{amount}} a Salvadanaio se tratan como ahorro, no como gasto.', 'savings.reviewLargest': 'La mayor salida fue de {{amount}} en {{name}}.', 'savings.reviewRecurring': '{{name}} aparece {{count}} veces; conviene comprobar si es un gasto previsto o reducible.', 'savings.reviewNoRecurring': 'No destaca ninguna descripción de gasto repetida en este periodo.', 'savings.reviewEmpty': 'Todavía no hay suficientes Movimientos de Intesa sincronizados para un análisis honesto. Actualiza la cuenta conectada y esta sección usará los datos reales.', 'savings.momentumStart': 'Añade el saldo de Salvadanaio para establecer el primer punto real hacia el objetivo W212.', 'savings.momentumFirst': 'Has reservado {{amount}}. Mantén el precio de compra separado de seguro, mantenimiento y matriculación.', 'savings.momentumUp': 'El ahorro aumentó {{amount}} desde la semana registrada anterior. Es un buen impulso: hazlo sostenible.', 'savings.momentumDown': 'El ahorro bajó {{amount}} desde la semana registrada anterior. Sin juzgar: revisa Movimientos, identifica qué cambió y fija el siguiente paso realista.', 'savings.reviewNote': 'Generado localmente a partir de tus Movimientos reales y el historial de Salvadanaio; no se envían detalles a un servicio de IA. Orientación presupuestaria, no asesoramiento financiero.',
    'pages.financialServices': 'Servicios financieros', 'pages.loyalty': 'Programas de fidelización', 'pages.journeys': 'Viajes', 'pages.travelEmptyTitle': 'Aún no hay viajes', 'pages.travelEmptyText': 'Tus planes de viaje aparecerán aquí cuando quieras añadirlos.',
    'settings.integrations': 'Integraciones', 'settings.gmailText': 'Solo se muestra el estado de conexión. El acceso al correo está desactivado.', 'settings.supabaseText': 'Autenticación, datos privados y almacenamiento de documentos.', 'settings.bankingText': 'Saldos y movimientos de solo lectura. Los pagos están desactivados.', 'settings.privacy': 'Privacidad', 'settings.privateByDesign': 'Privado desde el diseño', 'settings.privacyText': 'Los identificadores solo aparecen después de autenticarte. Las respuestas sensibles de las API nunca se almacenan en caché mediante el service worker.',
    'settings.personalisation': 'Personalización', 'settings.appearance': 'Apariencia', 'settings.appearanceText': 'Elige el estilo visual que te resulte más cómodo.', 'settings.light': 'Claro', 'settings.dark': 'Oscuro', 'settings.language': 'Idioma', 'settings.languageText': 'Elige el idioma utilizado en todo Private Hub.', 'settings.english': 'English', 'settings.italian': 'Italiano', 'settings.spanish': 'Español', 'settings.security': 'Seguridad', 'settings.password': 'Contraseña', 'settings.passwordText': 'Establece o cambia la contraseña utilizada para iniciar sesión.', 'settings.newPassword': 'Nueva contraseña', 'settings.confirmPassword': 'Confirmar contraseña', 'settings.setPassword': 'Establecer contraseña', 'settings.passwordMismatch': 'Las contraseñas no coinciden.', 'settings.passwordFailed': 'No se pudo guardar la contraseña.', 'settings.passwordSaved': 'Contraseña guardada.',
    'country.Italy': 'Italia', 'country.Brazil': 'Brasil',
    'identifier.Email': 'Correo electrónico', 'identifier.IBAN': 'IBAN', 'identifier.Chave PIX': 'Chave PIX',
    'document.Passport': 'Pasaporte', 'document.Carta d’identità': 'Carta d’identità', 'document.Carta d\'identità': 'Carta d’identità', 'document.Tessera Sanitaria': 'Tessera Sanitaria', 'document.Patente italiana': 'Patente italiana', 'document.RG': 'RG', 'document.CPF': 'CPF', 'document.CNH': 'CNH', 'document.Payslips': 'Nóminas', 'document.Miscellaneous': 'Varios',
  },
}

const localeByLanguage: Record<Language, string> = { en: 'en-GB', it: 'it-IT', es: 'es-ES' }
const PreferencesContext = createContext<PreferencesValue | null>(null)

function readLanguage(): Language {
  const stored = localStorage.getItem('private-hub-language')
  return stored === 'it' || stored === 'es' ? stored : 'en'
}

function readTheme(): Theme {
  return localStorage.getItem('private-hub-theme') === 'dark' ? 'dark' : 'light'
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>(readTheme)
  const [language, setLanguage] = useState<Language>(readLanguage)

  useEffect(() => {
    localStorage.setItem('private-hub-theme', theme)
    document.documentElement.dataset.theme = theme
    document.documentElement.style.colorScheme = theme
    document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')?.setAttribute('content', theme === 'dark' ? '#101722' : '#edf4fb')
  }, [theme])

  useEffect(() => {
    localStorage.setItem('private-hub-language', language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<PreferencesValue>(() => {
    const t = (key: string, vars: Record<string, string | number> = {}) => {
      const template = dictionaries[language][key] ?? dictionaries.en[key] ?? key
      return Object.entries(vars).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template)
    }
    return {
      theme,
      setTheme,
      language,
      setLanguage,
      t,
      locale: localeByLanguage[language],
      countryName: (country) => { if (!country) return ''; const key = `country.${country}`; const value = t(key); return value === key ? country : value },
      documentName: (documentType) => { const key = `document.${documentType}`; const value = t(key); return value === key ? documentType : value },
      identifierName: (identifierType) => { if (!identifierType) return ''; const key = `identifier.${identifierType}`; const value = t(key); return value === key ? identifierType : value },
    }
  }, [language, theme])

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}

export function usePreferences() {
  const value = useContext(PreferencesContext)
  if (!value) throw new Error('usePreferences must be used inside PreferencesProvider')
  return value
}
